// <auto-generated />
using InstrumentalistFinderApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace InstrumentalistFinderApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220817062250_Initial-Migration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("InstrumentalistFinderApi.Models.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Message = "I need a church to play for. No fees "
                        },
                        new
                        {
                            Id = 2,
                            Message = "Im a professional drummer looking for a choir to grow with. No fees required"
                        },
                        new
                        {
                            Id = 3,
                            Message = "I'm available for programmes. Dm to discuss fees "
                        },
                        new
                        {
                            Id = 4,
                            Message = "On my way to a church programme "
                        },
                        new
                        {
                            Id = 5,
                            Message = "I need a church to play for. "
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
